services:
  - type: web
    name: url-shortener-api
    runtime: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
    healthCheckPath: /api/health